SET(CPACK_GENERATOR "NSIS")

SET(PACKAGE_EXCLUDE_PLATFORM ".desktop|${ORG_PROJECT_NAME}.so|openConfiguratorWrapper.so") #|/*.so
SET(CPACK_PACKAGE_FILE_NAME "${ORG_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}-win32-x86")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "!define MUI_HEADERIMAGE_BITMAP \\\".\\\\${CPACK_PACKAGE_FILE_NAME}\\\\images\\\\openConfig.bmp\\\"")
SET(CPACK_CREATE_DESKTOP_LINKS "${ORG_PROJECT_NAME}.exe")

SET(CPACK_PACKAGE_INSTALL_DIRECTORY "${ORG_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${ORG_PROJECT_NAME}")

SET(CPACK_NSIS_DISPLAY_NAME "${ORG_PROJECT_NAME}")
SET(CPACK_NSIS_INSTALLED_ICON_NAME "\\\\${ORG_PROJECT_NAME}.exe")
SET(CPACK_NSIS_PACKAGE_NAME "${ORG_PROJECT_NAME} ${CPACK_PACKAGE_VERSION}")
SET(CPACK_NSIS_CREATE_ICONS "CreateShortCut \\\"$SMPROGRAMS\\\\$STARTMENU_FOLDER\\\\${ORG_PROJECT_NAME}.lnk\\\" \\\"$INSTDIR\\\\${ORG_PROJECT_NAME}.exe\\\"")
SET(CPACK_NSIS_CREATE_ICONS_EXTRA "CreateShortCut  \\\"$DESKTOP\\\\${ORG_PROJECT_NAME}.lnk\\\" \\\"$INSTDIR\\\\${ORG_PROJECT_NAME}.exe\\\"")
SET(CPACK_NSIS_DELETE_ICONS_EXTRA "Delete \\\"$SMPROGRAMS\\\\$MUI_TEMP\\\\${ORG_PROJECT_NAME}.lnk\\\" \\n Delete \\\"$DESKTOP\\\\${ORG_PROJECT_NAME}.lnk\\\"")
SET(CPACK_NSIS_HELP_LINK "http://sourceforge.net/p/openconf/discussion/")
SET(CPACK_NSIS_URL_INFO_ABOUT "http://www.kalycito.com")
SET(CPACK_NSIS_CONTACT "powerlink-team@kalycito.com")            
SET(CPACK_NSIS_MUI_FINISHPAGE_RUN "..\\\\${ORG_PROJECT_NAME}.exe")

SET(CPACK_PACKAGE_DEFAULT_LOCATION ".")

SET(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")



#SET(CPACK_NSIS_INSTALLER_ICON_CODE "!define MUI_ICON \\\"${CMAKE_CURRENT_SOURCE_DIR}/images/openConfig.ico\\\"")
#SET(CPACK_PACKAGE_DEFAULT_LOCATION "${ORG_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}")
#SET(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_SOURCE_DIR}/openConfig.ico")
#This only creates windows 8 menu?
#SET(CPACK_PACKAGE_EXECUTABLES "${ORG_PROJECT_NAME}" "openCONFIGURATOR executable")